CREATE TABLE EMAIL (
  ID INT AUTO_INCREMENT, 
  USERNAME VARCHAR(100) NOT NULL, 
  DATE DATE NOT NULL, 
  IMAGE TEXT, 
  MESSAGE TEXT, 
  PRIMARY KEY (ID)
);
  
CREATE TABLE FAVORITELINKS (
  ID INTEGER AUTO_INCREMENT NOT NULL, 
  NAME TEXT, 
  URL TEXT, 
  DESCR TEXT, 
  PRIMARY KEY (ID)
);

CREATE TABLE ABOUTME ( 
  ID INT AUTO_INCREMENT, 
  YEAR YEAR NOT NULL, 
  DATA TEXT, 
  PRIMARY KEY (ID) 
);

CREATE TABLE SPIRIT_ANIMAL (
  ID INT AUTO_INCREMENT NOT NULL, 
  NAME TEXT, 
  URL TEXT, 
  PRIMARY KEY (ID)
)

CREATE TABLE FULL_STACK (
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,           
  NAME VARCHAR(255),  
  DESCR TEXT,     
  UNIQUE KEY unique_name (NAME)       
);

CREATE TABLE EMBEDDED ( 
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,            
  NAME VARCHAR(255),  
  DESCR TEXT ,     
  UNIQUE KEY unique_name (NAME)       
);

CREATE TABLE CODE ( 
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,                
  NAME VARCHAR(255),  
  DESCR TEXT ,     
  UNIQUE KEY unique_name (NAME)       
);

CREATE TABLE SPECIAL_PROJECTS ( 
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,    
  NAME VARCHAR(255),  
  DESCR TEXT ,     
  UNIQUE KEY unique_name (NAME)       
);

CREATE TABLE FULL_STACK_RECORDS(
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,          
  NAME VARCHAR(255), TYPE ENUM('code', 'image', 'text'), 
  POSITION INTEGER,  
  DATA TEXT   
);

CREATE TABLE EMBEDDED_RECORDS(
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,            
  NAME VARCHAR(255), 
  TYPE ENUM('code', 'image', 'text'), 
  POSITION INTEGER,  
  DATA TEXT   
);

CREATE TABLE CODE_RECORDS(
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY  ,                
  NAME VARCHAR(255), 
  TYPE ENUM('code', 'image', 'text'), 
  POSITION INTEGER,  DATA TEXT   
);

CREATE TABLE SPECIAL_PROJECTS_RECORDS  (
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY  ,  
  NAME VARCHAR(255), 
  TYPE ENUM('code', 'image', 'text'), 
  POSITION INTEGER,  
  DATA TEXT   
);